import test from 'node:test';import assert from 'node:assert/strict';
import {metricsFromMeta,totalMetrics,ratio,analyticsProjection,type AnalyticsRow} from '../server/analytics-model.js';
import {analyticsApi} from '../server/analytics.js';import {config} from '../server/config.js';
const day='2026-09-25';
const raw={date_start:day,date_stop:day,spend:'785.69',impressions:'78298',reach:'73793',clicks:'1171',actions:[{action_type:'link_click',value:'835'},{action_type:'landing_page_view',value:'424'},{action_type:'omni_landing_page_view',value:'424'}]};
const row:AnalyticsRow={id:'123',campaignId:'123',postId:null,name:'Group',hasData:true,metrics:metricsFromMeta([raw],day,2)};
const snapshot={schemaVersion:1,id:'999-'+day,adAccountId:'999',reportDate:day,fetchedAt:'2026-09-26T10:00:00Z',currency:'INR',currencyDigits:2,source:'Hermoso / Meta Insights',campaigns:[row],ads:[{...row,id:'456'}],token:'do-not-return',totals:{spendMinor:999999}};
test('metrics use native minor units, link CTR and one landing-page action without double counting',()=>{assert.equal(row.metrics.spendMinor,78569);assert.equal(row.metrics.landingPageViews,424);assert.equal(row.metrics.shares,0);assert.equal(ratio(row.metrics.spendMinor,row.metrics.landingPageViews),78569/424);assert.equal(ratio(0,0),null);assert.throws(()=>metricsFromMeta([{...raw,date_stop:'2026-09-26'}],day,2));assert.throws(()=>metricsFromMeta([raw,raw],day,2));assert.throws(()=>metricsFromMeta([{...raw,spend:'-2'}],day,2));});
test('missing metrics remain unknown, zero stays zero, reach is never summed, totals are weighted',()=>{const empty=metricsFromMeta([],day,2);assert.equal(empty.impressions,null);assert.equal(empty.landingPageViews,null);const zero=metricsFromMeta([{date_start:day,date_stop:day,spend:'0',impressions:'0',actions:[]}],day,2);assert.equal(zero.spendMinor,0);assert.equal(zero.linkClicks,0);const totals=totalMetrics([row,{...row,id:'124'}]);assert.equal(totals.spendMinor,157138);assert.equal(totals.reach,null);assert.equal(totalMetrics([row,{...row,metrics:empty}]).spendMinor,null);});
test('projection drops unknown provider fields and rejects cross-campaign rows',()=>{const safe=analyticsProjection(snapshot);assert.equal('token'in safe,false);assert.equal(safe.totals.spendMinor,78569);assert.throws(()=>analyticsProjection({...snapshot,ads:[{...row,campaignId:'888'}]}));assert.throws(()=>analyticsProjection({...snapshot,campaigns:[row,row]}));assert.throws(()=>analyticsProjection({...snapshot,reportDate:'2026-02-31'}));});
test('analytics API is authenticated, workspace-scoped, bounded and read-only',async()=>{
 let touched=false;const paths:string[]=[];const query={orderBy:(field:string,direction:string)=>{assert.equal(field,'reportDate');assert.equal(direction,'desc');return query;},limit:(n:number)=>{assert.equal(n,31);return query;},get:async()=>({docs:[{data:()=>snapshot}],size:1})};
 const services={environment:'local',auth:{verifyIdToken:async()=>({uid:'u'}),getUser:async()=>({customClaims:{marketingWorkspaces:[config.workspaceId]}})},db:{collection:(name:string)=>{touched=true;paths.push(name);return{doc:(id:string)=>{paths.push(id);return{collection:(name:string)=>{paths.push(name);return query;}};}};}}};
 const req=(method='GET',token?:string,query={})=>({method,query,get:()=>token});let output:any;const res={json:(x:unknown)=>{output=x;}};
 await assert.rejects(analyticsApi(req() as never,res as never,services as never,'/marketing/analytics'),{status:401});assert.equal(touched,false);
 await assert.rejects(analyticsApi(req('POST','Bearer test') as never,res as never,services as never,'/marketing/analytics'),{status:405});
 await assert.rejects(analyticsApi(req('GET','Bearer test',{workspace:'other'}) as never,res as never,services as never,'/marketing/analytics'),{status:400});
 await analyticsApi(req('GET','Bearer test') as never,res as never,services as never,'/marketing/analytics');assert.deepEqual(paths,['marketingWorkspaces',config.workspaceId,'adAnalytics']);assert.equal(output.snapshots.length,1);assert.equal('token'in output.snapshots[0],false);
});
